/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemmangmentinformation.DPL.TaskManger;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import systemmangmentinformation.DBL.Static.Admin.AdminsUsersTask;
import systemmangmentinformation.DBL.Type.DisplayValueModel1;
import systemmangmentinformation.DBL.Vews.AdminVews.VoAdminsUsersTask;

/**
 *
 * @author shoeep
 */
public class TaskUserUpdate extends javax.swing.JFrame {

    /**
     * Creates new form TaskUserUpdate
     */
    public TaskUserUpdate() {
        initComponents();
                try {
       for(DisplayValueModel1 vo:AdminsUsersTask.getInstance().getFkFromTable())
         comNameTask.addItem(vo.toString());
          for(DisplayValueModel1 vo:AdminsUsersTask.getInstance().getFkFromUser())
      comUserTask.addItem(vo.toString());    
           for(DisplayValueModel1 vo:AdminsUsersTask.getInstance().getFkFromTypeID())
           comTypeUser.addItem(vo.toString());
           for(DisplayValueModel1 vo:AdminsUsersTask.getInstance().getFkFromMangerID())
           comMangerTask.addItem(vo.toString());
          
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdateTask = new javax.swing.JToggleButton();
        comTypeUser = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comNameTask = new javax.swing.JComboBox<>();
        comMangerTask = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comUserTask = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();
        btnExitTask = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        txtSearchTaskName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnumSearchTask = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        txtMangerTask = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblNameUsers = new javax.swing.JLabel();
        txtTypeUser = new javax.swing.JTextField();
        txtNameUsers = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNameUsers = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUpdateTask.setText("تعديل");
        btnUpdateTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTaskActionPerformed(evt);
            }
        });

        comTypeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comTypeUserActionPerformed(evt);
            }
        });

        jLabel3.setText("المهمة");

        comNameTask.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comNameTaskItemStateChanged(evt);
            }
        });
        comNameTask.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                comNameTaskHierarchyChanged(evt);
            }
        });
        comNameTask.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                comNameTaskComponentMoved(evt);
            }
        });
        comNameTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNameTaskActionPerformed(evt);
            }
        });

        jLabel4.setText("تاريخ الانضمام ");

        comUserTask.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comUserTaskItemStateChanged(evt);
            }
        });

        jLabel1.setText("مدير  المهمة");

        jLabel2.setText("المستخدمين");

        btnExitTask.setText("خروج");
        btnExitTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitTaskActionPerformed(evt);
            }
        });

        jLabel5.setText("الاسم المهمة");

        jLabel6.setText("رقم المهمة");

        jToggleButton2.setText("بحث");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("مدير  المهمة");

        jLabel8.setText("نوع المستخدم");

        lblNameUsers.setText("المستخدمين");

        jLabel10.setText("نوع المستخدم");

        jScrollPane1.setViewportView(listNameUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(txtSearchTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(txtnumSearchTask, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(155, 155, 155)
                        .addComponent(jToggleButton2)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(39, 39, 39)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMangerTask, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNameUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(txtTypeUser))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNameUsers, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnExitTask)
                            .addGap(31, 31, 31)
                            .addComponent(btnUpdateTask))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(comTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(comMangerTask, javax.swing.GroupLayout.Alignment.LEADING, 0, 147, Short.MAX_VALUE)
                                            .addComponent(comUserTask, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comNameTask, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel1))
                                .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(254, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtnumSearchTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMangerTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton2)
                            .addComponent(jLabel3))
                        .addGap(53, 53, 53)
                        .addComponent(jLabel10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameUsers)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNameUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(comNameTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comMangerTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGap(6, 6, 6)
                    .addComponent(comTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addComponent(comUserTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExitTask)
                        .addComponent(btnUpdateTask))
                    .addGap(72, 72, 72)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void setModel(){
        mode=    (DefaultListModel) listNameUsers.getModel();
}
    private void btnUpdateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTaskActionPerformed
        // TODO add your handling code here:
        
        
        VoAdminsUsersTask vo=new VoAdminsUsersTask();
 
            vo.setRecordID(Integer.parseInt(txtnumSearchTask.getText())); 
        
       
        vo.setIDTaskManger(new DisplayValueModel1(comMangerTask.getSelectedIndex(),comMangerTask.getSelectedItem()));
        vo.setIdUser(new DisplayValueModel1(comUserTask.getSelectedIndex(),comUserTask.getSelectedItem()));
        vo.setTypeID(new DisplayValueModel1(comTypeUser.getSelectedIndex(),comTypeUser.getSelectedItem()));
        vo.setTypeTasckManger(dateChooserCombo1.getText());
        vo.setTaskId(new DisplayValueModel1(comNameTask.getSelectedIndex(),comNameTask.getSelectedItem()));

    mode.addElement(evt);
        try {
            int rows=  AdminsUsersTask.getInstance().insert(vo);
            if(rows>0)
            {
                JOptionPane.showConfirmDialog(null,"update sucessfuly");

            }
        } catch (Exception ex) {
            Logger.getLogger(UserTask.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateTaskActionPerformed

    private void comTypeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comTypeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comTypeUserActionPerformed

    private void comNameTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNameTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comNameTaskActionPerformed

    private void btnExitTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitTaskActionPerformed
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitTaskActionPerformed

    private void comNameTaskHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_comNameTaskHierarchyChanged
        // TODO add your handling code here:
     
    }//GEN-LAST:event_comNameTaskHierarchyChanged

    private void comNameTaskComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_comNameTaskComponentMoved
        // TODO add your handling code here:
      int n=  comNameTask.getSelectedIndex()+1;
           txtSearchTaskName.setText(comNameTask.getSelectedItem().toString());
        
    }//GEN-LAST:event_comNameTaskComponentMoved

    private void comNameTaskItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comNameTaskItemStateChanged
        // TODO add your handling code here:
          txtSearchTaskName.setText(comNameTask.getSelectedItem().toString());
             txtnumSearchTask.setText( (1+comNameTask.getSelectedIndex())+"");
          
    }//GEN-LAST:event_comNameTaskItemStateChanged
    DefaultListModel<Object> mode;
    private void comUserTaskItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comUserTaskItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comUserTaskItemStateChanged

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        VoAdminsUsersTask vo1=new VoAdminsUsersTask();
        vo1.getTaskId().valueMember=txtnumSearchTask.getText();
        try {
        for(VoAdminsUsersTask vo :   AdminsUsersTask.getInstance().getUsers()){
         comUserTask.addItem(vo.getIdUser().toString());
        
     }    
        } catch (Exception e) {
        }
 
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskUserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskUserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskUserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskUserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskUserUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnExitTask;
    private javax.swing.JToggleButton btnUpdateTask;
    private javax.swing.JComboBox<String> comMangerTask;
    private javax.swing.JComboBox<String> comNameTask;
    private javax.swing.JComboBox<String> comTypeUser;
    private javax.swing.JComboBox<String> comUserTask;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblNameUsers;
    private javax.swing.JList<String> listNameUsers;
    private javax.swing.JTextField txtMangerTask;
    private javax.swing.JTextField txtNameUsers;
    private javax.swing.JTextField txtSearchTaskName;
    private javax.swing.JTextField txtTypeUser;
    private javax.swing.JTextField txtnumSearchTask;
    // End of variables declaration//GEN-END:variables
}
