/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemmangmentinformation.DPL.TaskManger;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import systemmangmentinformation.DAL.ConnectionClasses;
import systemmangmentinformation.DBL.Type.DisplayValueModel1;
import systemmangmentinformation.DBL.Static.Admin.AdminsUsersTask;
import systemmangmentinformation.DBL.Type.MethodDb;
import systemmangmentinformation.DBL.Vews.AdminVews.VoAdminsUsersTask;

/**
 *
 * @author shoeep
 */
public class UserTask extends javax.swing.JFrame {

    /**
     * Creates new form UserTask
     */
    public UserTask() {
       
            initComponents();
            try {
       for(DisplayValueModel1 vo:AdminsUsersTask.getInstance().getFkFromTable())
         comNameTask.addItem(vo.toString());
          for(DisplayValueModel1 vo:AdminsUsersTask.getInstance().getFkFromUser())
      comUserTask.addItem(vo.toString());    
           for(DisplayValueModel1 vo:AdminsUsersTask.getInstance().getFkFromTypeID())
           comTypeUser.addItem(vo.toString());
           for(DisplayValueModel1 vo:AdminsUsersTask.getInstance().getFkFromMangerID())
           comMangerTask.addItem(vo.toString());
        } catch (Exception e) {
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comMangerTask = new javax.swing.JComboBox<>();
        comUserTask = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnExitTask = new javax.swing.JToggleButton();
        btnAddTask = new javax.swing.JToggleButton();
        comTypeUser = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comNameTask = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblShowErrors = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("مدير  المهمة");

        jLabel2.setText("المستخدم الجديد");

        jToggleButton1.setText("نوع المستخدم");

        btnExitTask.setText("خروج");
        btnExitTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitTaskActionPerformed(evt);
            }
        });

        btnAddTask.setText("اضافة");
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });

        comTypeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comTypeUserActionPerformed(evt);
            }
        });

        jLabel3.setText("المهمة");

        comNameTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comNameTaskActionPerformed(evt);
            }
        });

        jLabel4.setText("تاريخ الانضمام ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(comMangerTask, javax.swing.GroupLayout.Alignment.LEADING, 0, 147, Short.MAX_VALUE)
                                        .addComponent(comUserTask, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comNameTask, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jToggleButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnExitTask)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAddTask)))
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 102, Short.MAX_VALUE))
                    .addComponent(lblShowErrors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblShowErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comNameTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comMangerTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(comTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comUserTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExitTask)
                    .addComponent(btnAddTask))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comNameTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comNameTaskActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comNameTaskActionPerformed

    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
        // TODO add your handling code here:
try{int rows=0;
    VoAdminsUsersTask vo=new VoAdminsUsersTask();
   vo.setIDTaskManger(new DisplayValueModel1(comMangerTask.getSelectedIndex(),comMangerTask.getSelectedItem()));
   vo.setIdUser(new DisplayValueModel1(comUserTask.getSelectedIndex(),comUserTask.getSelectedItem()));
   vo.setTypeID(new DisplayValueModel1(comTypeUser.getSelectedIndex(),comTypeUser.getSelectedItem()));
    vo.setTaskId(new DisplayValueModel1(comNameTask.getSelectedIndex(),comNameTask.getSelectedItem()));//.getSelectedIndex(),comTypeUser.getSelectedItem()));
   vo.setTypeTasckManger(dateChooserCombo1.getText());
   AdminsUsersTask.getInstance().insert(vo);
       if(rows>0)
 {
     JOptionPane.showConfirmDialog(null,"insert sucessfuly");
     
 }
}
catch(Exception ex){
    
}
    }//GEN-LAST:event_btnAddTaskActionPerformed

    private void comTypeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comTypeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comTypeUserActionPerformed

    private void btnExitTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitTaskActionPerformed
      this.setVisible(false);
       
// TODO add your handling code here:
    }//GEN-LAST:event_btnExitTaskActionPerformed
    private void searchManger() throws Exception {
        String sql = " select MangerId,MangerName from UserEmp ";

        ConnectionClasses conn = new ConnectionClasses();
        Statement statmnt = conn.getConnection().createStatement();
        ResultSet set = statmnt.executeQuery(sql);
        if (set.next()) {
            DisplayValueModel1 dis = new DisplayValueModel1(set.getString(2), set.getInt(1));
            dis.valueMember.toString();
            comNameTask.addItem(dis.toString());
        }
    }

    private void searchTasck() throws Exception {
        String sql = " select idTask,NameTask from Task ";

        ConnectionClasses conn = new ConnectionClasses();
        Statement statmnt = conn.getConnection().createStatement();
        ResultSet set = statmnt.executeQuery(sql);
        if (set.next()) {
            DisplayValueModel1 dis = new DisplayValueModel1(set.getString(2), set.getInt(1));
            dis.valueMember.toString();
            comNameTask.addItem(dis.toString());
        }
    }

    private void searchUserNew() throws Exception {

        String sql = " select IDUser,NameUser from UserEmp Where  IDTypeUser ";

        ConnectionClasses conn = new ConnectionClasses();
        Statement statmnt = conn.getConnection().createStatement();
        ResultSet set = statmnt.executeQuery(sql);
        if (set.next()) {
            DisplayValueModel1 dis = new DisplayValueModel1(set.getString(2), set.getInt(1));
            dis.valueMember.toString();
            comNameTask.addItem(dis.toString());
        }
    }

    private void searchTypeUserTask() throws Exception {
        String sql = " select IDTypeUser,NameTypeUser from TypeUser ";

        ConnectionClasses conn = new ConnectionClasses();
        Statement statmnt = conn.getConnection().createStatement();
        ResultSet set = statmnt.executeQuery(sql);
        if (set.next()) {
            DisplayValueModel1 dis = new DisplayValueModel1(set.getString(2), set.getInt(1));
            dis.valueMember.toString();
            comTypeUser.addItem(dis.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAddTask;
    private javax.swing.JToggleButton btnExitTask;
    private javax.swing.JComboBox<String> comMangerTask;
    private javax.swing.JComboBox<String> comNameTask;
    private javax.swing.JComboBox<String> comTypeUser;
    private javax.swing.JComboBox<String> comUserTask;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblShowErrors;
    // End of variables declaration//GEN-END:variables
}
