/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemmangmentinformation.DPL;
import systemmangmentinformation.DPL.Loginsystem.LoginSystem;
import systemmangmentinformation.DPL.Loginsystem.LogoOut;
import systemmangmentinformation.DPL.Tranceformation.Bransh;
import systemmangmentinformation.DPL.Tranceformation.Vilage;
import systemmangmentinformation.DPL.Tranceformation.Teacher;
import systemmangmentinformation.DPL.Tranceformation.School;
import systemmangmentinformation.DPL.TaskManger.TasckManger;
import systemmangmentinformation.DBL.Static.BranchDB;
import  systemmangmentinformation.DAL.ConnectionClasses;
import java.sql.*;
import java.awt.TextArea;
import systemmangmentinformation.DPL.ReportDB.RPT_Users;

/**
 *
 * @author shoeep
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        MenuCurentFile.enable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jColorChooser1 = new javax.swing.JColorChooser();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoginRecord = new javax.swing.JMenuItem();
        LogeOutRecored = new javax.swing.JMenuItem();
        WorkeCopy = new javax.swing.JMenuItem();
        SaveUpdateCurentNow = new javax.swing.JMenuItem();
        CopyTofileNow = new javax.swing.JMenuItem();
        MenuCurentFile = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CreateFolderNow = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ChangefileCurrentNow = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ChangeSittingNow = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        button1.setLabel("button1");

        button2.setLabel("button2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setFont(new java.awt.Font("AGA Arabesque", 1, 10)); // NOI18N
        setForeground(java.awt.Color.black);

        jPanel3.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton2.setText("الرساليات");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 170, 30));

        jToggleButton3.setText("الفروع");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, 40));

        jToggleButton4.setText("المدارس");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 170, 40));

        jToggleButton5.setText("المعلمين");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 170, 30));

        jToggleButton7.setText("النقل");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 170, 40));

        jToggleButton6.setText("المديريات");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, 40));

        jToggleButton8.setText("التقارير");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 170, 40));

        jToggleButton9.setText("الادارات");
        jPanel3.add(jToggleButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 170, 40));

        jToggleButton10.setText("المستخدمين");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 170, 40));

        jToggleButton11.setText("صلاحيات");
        jToggleButton11.setMaximumSize(new java.awt.Dimension(69, 23));
        jPanel3.add(jToggleButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 170, 40));

        jToggleButton12.setText("المدراء");
        jToggleButton12.setMaximumSize(new java.awt.Dimension(69, 23));
        jPanel3.add(jToggleButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 170, 40));

        jToggleButton13.setText("الاقسام");
        jPanel3.add(jToggleButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 170, 40));

        jToggleButton14.setText("جدول الحضور");
        jPanel3.add(jToggleButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, 40));

        jToggleButton15.setText("المهام");
        jToggleButton15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(jToggleButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        jPanel4.setAutoscrolls(true);
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jColorChooser1, org.jdesktop.beansbinding.ELProperty.create("${background}"), jMenuBar1, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        jMenu1.setText("ملف");

        LoginRecord.setText("تسجيل الدخول");
        LoginRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginRecordActionPerformed(evt);
            }
        });
        jMenu1.add(LoginRecord);

        LogeOutRecored.setText("تسجيل الخروج");
        LogeOutRecored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogeOutRecoredActionPerformed(evt);
            }
        });
        jMenu1.add(LogeOutRecored);

        WorkeCopy.setText("عمل نسخة احتياطية");
        jMenu1.add(WorkeCopy);

        SaveUpdateCurentNow.setText("حفض التعديلال ت الحالية الملف");
        jMenu1.add(SaveUpdateCurentNow);

        CopyTofileNow.setText("نسخ الى ملف");
        jMenu1.add(CopyTofileNow);

        MenuCurentFile.setText("القوائم الحالية");
        jMenu1.add(MenuCurentFile);
        jMenu1.add(jSeparator2);

        jMenuItem10.setText("ملف جديد");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("التحرير");

        CreateFolderNow.setText("انشاء ملف ");
        jMenu2.add(CreateFolderNow);

        jMenuItem8.setText("انشاء مجلد");
        jMenu2.add(jMenuItem8);
        jMenu2.add(jSeparator1);

        ChangefileCurrentNow.setText("تغير اسم ملف");
        jMenu2.add(ChangefileCurrentNow);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("العرض");

        ChangeSittingNow.setText("تغير اعدادات الوجهة الحالية");
        jMenu5.add(ChangeSittingNow);

        jMenuItem11.setText("اعدادات متقدمة");
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("التقارير");

        jMenuItem12.setText("تقارير شهرية");
        jMenu7.add(jMenuItem12);

        jMenuItem13.setText("تقارير اسبوعية");
        jMenu7.add(jMenuItem13);

        jMenuItem14.setText("انشاء تقرير جديد");
        jMenu7.add(jMenuItem14);
        jMenu7.add(jSeparator3);

        jMenuItem15.setText("نسخ تقارير");
        jMenu7.add(jMenuItem15);

        jMenuItem16.setText("انشاء تقارير من خلال استعلام ");
        jMenu7.add(jMenuItem16);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("النافذة");

        jMenuItem17.setText("عمل اختصارات ");
        jMenu8.add(jMenuItem17);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("المساعدة");

        jMenuItem18.setText("معلومات عن القائمة الرئيسية ");
        jMenu9.add(jMenuItem18);

        jMenuItem19.setText("الوجهات الفرعية");
        jMenu9.add(jMenuItem19);
        jMenu9.add(jSeparator4);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("الاعدادات");

        jMenuItem20.setText("اعدادات  اضافية");
        jMenuItem20.setAlignmentX(5.0F);
        jMenuItem20.setAlignmentY(5.0F);
        jMenu10.add(jMenuItem20);

        jMenuItem3.setText("الاعداد المضهر");
        jMenuItem3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenuItem3FocusGained(evt);
            }
        });
        jMenu10.add(jMenuItem3);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("للتواصل معنا");

        jMenu13.setText("صيانة");

        jMenuItem7.setText("بيانات الجهزة");
        jMenu13.add(jMenuItem7);

        jMenuItem9.setText("نوع الصيانة");
        jMenu13.add(jMenuItem9);

        jMenuItem21.setText("jMenuItem21");
        jMenu13.add(jMenuItem21);

        jMenu11.add(jMenu13);

        jMenuBar1.add(jMenu11);

        jMenu12.setText("التوثيق");

        jMenuItem26.setText("اضافة وثيقة");
        jMenu12.add(jMenuItem26);

        jMenuItem27.setText("عرض وثائق النظام");
        jMenu12.add(jMenuItem27);

        jMenuItem28.setText("اعدادات الوثائق");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem28);

        jMenuBar1.add(jMenu12);

        jMenu6.setText("المهام");

        jMenuItem4.setText("المهام الحالية");
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("المهام المنجزة");
        jMenu6.add(jMenuItem5);

        jMenuItem6.setText("ادارة المهام");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuBar1.add(jMenu6);

        jMenu14.setText("شكوي");

        jMenuItem22.setText("عرض الشكوي");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem22);

        jMenuItem23.setText("ادارة الشكوي ");
        jMenu14.add(jMenuItem23);

        jMenuItem24.setText("مؤشر الشكوى");
        jMenu14.add(jMenuItem24);

        jMenuItem25.setText("الشكوى الجديدة");
        jMenu14.add(jMenuItem25);

        jMenuBar1.add(jMenu14);

        jMenu15.setText("التقيمات");

        jMenuItem29.setText("تقيم طلاب");
        jMenu15.add(jMenuItem29);

        jMenuItem30.setText("تقيم طالبات");
        jMenu15.add(jMenuItem30);

        jMenuItem31.setText("تقيم مرحالي");
        jMenu15.add(jMenuItem31);

        jMenuItem32.setText("تقيم للمدارس");
        jMenu15.add(jMenuItem32);

        jMenuBar1.add(jMenu15);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogeOutRecoredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogeOutRecoredActionPerformed
        // TODO add your handling code here:
     LogoOut out=new LogoOut();
       
     out.setVisible(true );
     
    }//GEN-LAST:event_LogeOutRecoredActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuItem3FocusGained
jColorChooser1.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3FocusGained

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        
        Bransh bran=new Bransh();
        bran.setVisible(true);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
  Teacher teacher=new Teacher();
  teacher.setVisible(true);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
            School schol=new School();
        schol.setVisible(true);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        Vilage vil=new Vilage();
        vil.setVisible(true);
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
        Extension extension=new Extension();
        extension.setVisible(true);
        
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void LoginRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginRecordActionPerformed
        // TODO add your handling code here:
        
        LoginSystem login=new LoginSystem();
        login.setVisible(true);
    }//GEN-LAST:event_LoginRecordActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        TasckManger mangerTask=new  TasckManger();
        mangerTask.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
        MangmentUser mangment=new MangmentUser();
        mangment.setVisible(true);
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
       ShowProblem prob=new  ShowProblem();
       prob.setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
  RPT_Users rbt=new 
          RPT_Users();
  rbt.setVisible(true);
  
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ChangeSittingNow;
    private javax.swing.JMenuItem ChangefileCurrentNow;
    private javax.swing.JMenuItem CopyTofileNow;
    private javax.swing.JMenuItem CreateFolderNow;
    private javax.swing.JMenuItem LogeOutRecored;
    private javax.swing.JMenuItem LoginRecord;
    private javax.swing.JMenuItem MenuCurentFile;
    private javax.swing.JMenuItem SaveUpdateCurentNow;
    private javax.swing.JMenuItem WorkeCopy;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
