/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemmangmentinformation.DPL;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import systemmangmentinformation.DBL.Static.UserLogin.UsersMangmentDB;
import systemmangmentinformation.DBL.Type.DisplayValueModel1;
import systemmangmentinformation.DBL.Vews.MangmentUsers.VoUsersMangment;

/**
 *
 * @author shoeep
 */
public class UserDeprtment extends javax.swing.JFrame {

    /**
     * Creates new form UserDeprtment
     */
    public UserDeprtment() {
        initComponents();
        try {
            for(DisplayValueModel1 vo: UsersMangmentDB.getInstance().getFkFromTable())
            comMangmentUser.addItem(vo.toString());
                 for(DisplayValueModel1 vo: UsersMangmentDB.getInstance().getFkFromTableTypeUsers())
            comTypeUser.addItem(vo.toString());
        } 
        catch (Exception ex) {
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNameUser = new javax.swing.JTextField();
        txtPassord = new javax.swing.JPasswordField();
        txtPasswordChick = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comTypeUser = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnExiteUser = new javax.swing.JToggleButton();
        btnAddUser = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        comMangmentUser = new javax.swing.JComboBox<>();
        btnAddTaskForUser = new javax.swing.JToggleButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("الاسم المستخدم");

        txtNameUser.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtPassord.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtPasswordChick.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPasswordChick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordChickActionPerformed(evt);
            }
        });

        jLabel2.setText("رمز المستخدم");

        jLabel3.setText("تكيد رمز");

        comTypeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comTypeUserActionPerformed(evt);
            }
        });

        jLabel4.setText("نوع المستخدم");

        btnExiteUser.setText("خروج");
        btnExiteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExiteUserActionPerformed(evt);
            }
        });

        btnAddUser.setText("اضافة");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        jLabel5.setText("اسم الموضف");

        btnAddTaskForUser.setText("اضافة مهمة الى الستخدم  ");
        btnAddTaskForUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskForUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPassord, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txtPasswordChick))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnExiteUser)
                            .addGap(80, 80, 80)
                            .addComponent(btnAddUser))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(comMangmentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddTaskForUser)
                    .addComponent(jLabel5))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordChick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comMangmentUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnAddTaskForUser)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExiteUser)
                    .addComponent(btnAddUser))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordChickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordChickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordChickActionPerformed

    private void btnExiteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExiteUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnExiteUserActionPerformed

    private void btnAddTaskForUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskForUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTaskForUserActionPerformed

    private void comTypeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comTypeUserActionPerformed
       
    }//GEN-LAST:event_comTypeUserActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        if(txtNameUser.getText().isEmpty()||txtNameUser.getText().isEmpty()||txtPasswordChick.getText().isEmpty()){
            JOptionPane.showConfirmDialog(null, "ادخل الاسم ورمز دخول  من ضصلك");
            
            return;
        }
        if(!txtPassord.getText().equals(txtPasswordChick.getText())){
          JOptionPane.showConfirmDialog(null, "تاكيد رمز دخولغير صحياح");
            
            return;
        }
        VoUsersMangment vo=new VoUsersMangment();
        vo.setNameUser(txtNameUser.getText());
        vo.setPassword(txtPassord.getText());
       vo.setIDEmp(new DisplayValueModel1(comMangmentUser.getSelectedIndex()+1,comTypeUser.getSelectedItem()));
       vo.setTypeID(new DisplayValueModel1(comTypeUser.getSelectedIndex()+1, comTypeUser.getSelectedIndex()));
        try {
         int rows=   UsersMangmentDB.getInstance().insert(vo);
         if(rows>0){
                 JOptionPane.showConfirmDialog(null, "تم اضافة صف بنجاح");
       return;
         }
        } catch (Exception ex) {
              JOptionPane.showConfirmDialog(null,ex);
          //  Logger.getLogger(UserDeprtment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDeprtment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDeprtment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDeprtment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDeprtment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new UserDeprtment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAddTaskForUser;
    private javax.swing.JToggleButton btnAddUser;
    private javax.swing.JToggleButton btnExiteUser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> comMangmentUser;
    private javax.swing.JComboBox<String> comTypeUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField txtNameUser;
    private javax.swing.JPasswordField txtPassord;
    private javax.swing.JPasswordField txtPasswordChick;
    // End of variables declaration//GEN-END:variables
}
