/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemmangmentinformation.DPL.Tranceformation;




import systemmangmentinformation.DBL.Static.BranchDB;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;


import systemmangmentinformation.DBL.Vews.Information.VoBranch;

import systemmangmentinformation.Validition.Validation;
/**
 *
 * @author shoeep
 */

public class Bransh extends javax.swing.JFrame {

    /**
     * Creates new form Bransh
     */
    public Bransh() {
        initComponents();
     
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        txtnumBranch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNameBranch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnDelatebranch = new javax.swing.JToggleButton();
        btnAddBranch = new javax.swing.JToggleButton();
        btnSearchBranch = new javax.swing.JToggleButton();
        btnNewBranch = new javax.swing.JToggleButton();
        btnUpdateBranch = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabBranch = new javax.swing.JTable();
        lblFormtion = new javax.swing.JLabel();
        ntnClose = new javax.swing.JToggleButton();
        btnSearchAllBranch = new javax.swing.JToggleButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        txtnumBranch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setText("رقم الشعبة");

        txtNameBranch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setText("ااسم شعبة");

        btnDelatebranch.setText("حذف");
        btnDelatebranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelatebranchActionPerformed(evt);
            }
        });

        btnAddBranch.setText("اضافة");
        btnAddBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBranchActionPerformed(evt);
            }
        });

        btnSearchBranch.setText("بحث");
        btnSearchBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBranchActionPerformed(evt);
            }
        });

        btnNewBranch.setText("جديد");
        btnNewBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewBranchActionPerformed(evt);
            }
        });

        btnUpdateBranch.setText("تعديل");
        btnUpdateBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBranchActionPerformed(evt);
            }
        });

        tabBranch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "اسم الشعبة", "رقم الفرع", "ترتيب"
            }
        ));
        tabBranch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabBranch.setDoubleBuffered(true);
        tabBranch.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tabBranchComponentAdded(evt);
            }
        });
        tabBranch.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabBranchAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabBranch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabBranchFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(tabBranch);

        ntnClose.setText("اغلاق");
        ntnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntnCloseActionPerformed(evt);
            }
        });

        btnSearchAllBranch.setText("بحث كل");
        btnSearchAllBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAllBranchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDelatebranch)
                .addGap(51, 51, 51)
                .addComponent(btnUpdateBranch)
                .addGap(45, 45, 45)
                .addComponent(btnSearchBranch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btnAddBranch)
                .addGap(71, 71, 71)
                .addComponent(btnNewBranch)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNameBranch, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(txtnumBranch))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSearchAllBranch))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(lblFormtion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ntnClose)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnumBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNameBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnSearchAllBranch)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ntnClose)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFormtion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelatebranch)
                            .addComponent(btnUpdateBranch)
                            .addComponent(btnSearchBranch)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNewBranch)
                            .addComponent(btnAddBranch))))
                .addContainerGap())
        );

        btnDelatebranch.getAccessibleContext().setAccessibleName("btnDealte");
        btnAddBranch.getAccessibleContext().setAccessibleName("btnAdd");
        btnSearchBranch.getAccessibleContext().setAccessibleName("btnSearch");
        btnNewBranch.getAccessibleContext().setAccessibleName("btnNew");
        btnUpdateBranch.getAccessibleContext().setAccessibleName("btnUpdate");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBranchActionPerformed
        
       
    }//GEN-LAST:event_btnNewBranchActionPerformed
private void searchJtable()throws Exception{

     
}
    private void btnAddBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBranchActionPerformed
     if(txtNameBranch.getText().isEmpty()){
         JOptionPane.showConfirmDialog(null, "insert into NameBranch");
         return ;
         
     }
     VoBranch vo=new VoBranch();
     vo.setNameBranch(txtNameBranch.getText());
        try {
      int rows=      BranchDB.getInnstsnce().insert(vo);
      if(rows>0){
          JOptionPane.showConfirmDialog(null, "adds row sucessful");
      }
        } catch (Exception ex) {
            Logger.getLogger(Bransh.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    }//GEN-LAST:event_btnAddBranchActionPerformed
//update here
    private void btnUpdateBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBranchActionPerformed

     String Name=     txtNameBranch.getText();
    int id=    Integer.valueOf(txtnumBranch.getText()); 
    try{
    VoBranch vo=new VoBranch();     
    vo.setIDBranch(id);
    vo.setNameBranch(Name);        
   int rows   =   BranchDB.getInnstsnce().update(vo);  
   if(rows>0){
  JOptionPane.showConfirmDialog(null,"update is sucessfuly");}
     }catch(Exception ex){
    JOptionPane.showConfirmDialog(this,ex);
    }
    }                                               
 DefaultTableModel mod;
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
   setTable();
   mod.setNumRows(0);
   VoBranch scol=new VoBranch();
   List<VoBranch> vo =new Vector<>();
   mod.setNumRows(0);   
   try{  
   for(VoBranch vo1 : BranchDB.getInnstsnce().getAllElement()){
   Object []ob1={vo1.getIDBranch(),vo1.getNameBranch()};
   mod.addRow(ob1);}                                          }    
   catch(Exception ex) {JOptionPane.showConfirmDialog(null, ex); }                      
    }//GEN-LAST:event_btnUpdateBranchActionPerformed

    private void btnDelatebranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelatebranchActionPerformed

        int row1=removeFromTable();
        if(row1<0){
         JOptionPane.showConfirmDialog(null, "selected is empty ");
          return;
          }
          VoBranch vo=new VoBranch();
          vo.setNameBranch(mod.getValueAt(row1, 0).toString());
          vo.setIDBranch(Integer.parseInt( mod.getValueAt(row1, 1).toString()));
          try{
          int isdeleted=     BranchDB.getInnstsnce().delete(vo);
         if(isdeleted>0){
         JOptionPane.showConfirmDialog(null, "deleted is sucessfuly ");}}
         catch(Exception ex){
          JOptionPane.showConfirmDialog(null, ex); }    
    }//GEN-LAST:event_btnDelatebranchActionPerformed

    private void btnSearchBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBranchActionPerformed
  if(!txtnumBranch.isEnabled()){
  txtNameBranch.enable(true);
  txtnumBranch.enable(true);
  return;
   }
  if(txtnumBranch.getText().isEmpty()& txtNameBranch.getText().isEmpty()){
  JOptionPane.showConfirmDialog(null, "insert into fileds");
   return;
   }
   if(Validation.isDigeit(txtnumBranch.getText()) &Validation.isText(txtNameBranch.getText())){
   JOptionPane.showConfirmDialog(null, "insert number fileds");
    return;        
    }  
    int id=0;
    String Name="";
    id=    Integer.parseInt(txtnumBranch.getText()); 
    Name=    txtNameBranch.getText();
    try{        
    setTable();
    mod.setNumRows(0);
    VoBranch branch=new VoBranch();
     branch.setIDBranch(id);
     branch.setNameBranch(Name);
     VoBranch   sckole   =      BranchDB.getInnstsnce().search(branch);
    setTable();
    Object [] tab={sckole.getNameBranch(),sckole.getIDBranch()};
    mod.addRow(tab);
    }catch(Exception ex){
   JOptionPane.showConfirmDialog(this,ex);
    }
        
    }//GEN-LAST:event_btnSearchBranchActionPerformed

    private void tabBranchAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabBranchAncestorAdded


        // TODO add your handling code here:
    }//GEN-LAST:event_tabBranchAncestorAdded

    private void tabBranchComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tabBranchComponentAdded
        try {
            // TODO add your handling code here:
            searchJtable();
        } catch (Exception ex) {
            Logger.getLogger(Bransh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabBranchComponentAdded

    private void tabBranchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabBranchFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_tabBranchFocusGained

    private void ntnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntnCloseActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
    }//GEN-LAST:event_ntnCloseActionPerformed

    private void btnSearchAllBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAllBranchActionPerformed
       setTable();
        try{ 
            
            
            for(VoBranch vo1 : BranchDB.getInnstsnce().getAllElement()){
             Object []obj=  {vo1.getNameBranch(),vo1.getIDBranch()};
          mod.addRow(obj);
        
         }
        }catch(Exception ex){
        
        JOptionPane.showConfirmDialog(null, ex);
    }
    }//GEN-LAST:event_btnSearchAllBranchActionPerformed

private int  removeFromTable( ){
    setTable();
    CurrentRow=tabBranch.getSelectedRow();
         
         //   mod.getValueAt( "",row, row);
         mod.removeRow(CurrentRow);
         
         return CurrentRow;
}

int CurrentRow;

private void setTable(){
     mod =(DefaultTableModel ) tabBranch.getModel();

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bransh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bransh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bransh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bransh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bransh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAddBranch;
    private javax.swing.JToggleButton btnDelatebranch;
    private javax.swing.JToggleButton btnNewBranch;
    private javax.swing.JToggleButton btnSearchAllBranch;
    private javax.swing.JToggleButton btnSearchBranch;
    private javax.swing.JToggleButton btnUpdateBranch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFormtion;
    private javax.swing.JToggleButton ntnClose;
    private javax.swing.JTable tabBranch;
    private javax.swing.JTextField txtNameBranch;
    private javax.swing.JTextField txtnumBranch;
    // End of variables declaration//GEN-END:variables
}
