/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemmangmentinformation.DPL.Tranceformation;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.Vector;
import systemmangmentinformation.DAL.ConnectionClasses;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.DatatypeConverter;


import systemmangmentinformation.DBL.Static.SchoolINFDB;
import static systemmangmentinformation.DBL.Static.SchoolINFDB.getInstance;


import systemmangmentinformation.DBL.Type.DisplayValueModel1;
import systemmangmentinformation.DBL.Type.MethodDb;
import systemmangmentinformation.DBL.Vews.Information.VoSchool;

import systemmangmentinformation.Validition.Validation;

/**
 *
 * @author shoeep
 */
public class School extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public School(){
        initComponents();
      try{
     for(DisplayValueModel1    vo:SchoolINFDB.getInstance().getFkFromTable() ){
    txtNumSchool.enable(false);
    txtNameSchool.enable(false);
    //this.
      comVilage.addItem(vo.toString());
     
     }
      }catch(Exception ex){
          
      }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumSchool = new javax.swing.JTextField();
        txtNameSchool = new javax.swing.JTextField();
        lblNumSchool = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabSchool = new javax.swing.JTable();
        btnDelateSchoole = new javax.swing.JToggleButton();
        addSchool = new javax.swing.JToggleButton();
        searchSchool = new javax.swing.JToggleButton();
        newSchool = new javax.swing.JToggleButton();
        btnupdateSchole = new javax.swing.JToggleButton();
        comVilage = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        txtNumSchool.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtNameSchool.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNameSchool.setNextFocusableComponent(comVilage);

        lblNumSchool.setText("     رقم المدرسة");

        jLabel2.setText("اسم المدرسة");

        jLabel3.setText("اسم المديرية");

        tabSchool.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "اسم المديرية", "اسم المدرسة", "رقم المدرسة"
            }
        ));
        jScrollPane1.setViewportView(tabSchool);

        btnDelateSchoole.setText("حذف");
        btnDelateSchoole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelateSchooleActionPerformed(evt);
            }
        });

        addSchool.setText("اضافة");
        addSchool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSchoolActionPerformed(evt);
            }
        });

        searchSchool.setText("بحث");
        searchSchool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSchoolActionPerformed(evt);
            }
        });

        newSchool.setText("جديد");
        newSchool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSchoolActionPerformed(evt);
            }
        });

        btnupdateSchole.setText("تعديل");
        btnupdateSchole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateScholeActionPerformed(evt);
            }
        });

        jToggleButton1.setText("بحث كل");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setBackground(new java.awt.Color(255, 0, 51));
        jToggleButton2.setText("اغلاق");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(txtNameSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelateSchoole)
                        .addGap(51, 51, 51)
                        .addComponent(btnupdateSchole)
                        .addGap(45, 45, 45)
                        .addComponent(searchSchool)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addSchool)
                        .addGap(71, 71, 71)
                        .addComponent(newSchool))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(comVilage, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(txtNumSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(lblNumSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton2)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jToggleButton2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumSchool))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comVilage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jToggleButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelateSchoole)
                        .addComponent(btnupdateSchole)
                        .addComponent(searchSchool))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newSchool)
                        .addComponent(addSchool)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelateSchooleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelateSchooleActionPerformed
          
     int row1=removeFromTable();
        if(row1<0){
         JOptionPane.showConfirmDialog(null, "selected is empty ");
          return;
          }
          VoSchool vo=new VoSchool();
          
          vo.setNameSchool(mod.getValueAt(row1, 1).toString());
          try{
          int isdeleted=     SchoolINFDB.getInstance().delete(vo);
         if(isdeleted>0){
         JOptionPane.showConfirmDialog(null, "deleted is sucessfuly ");}}
         catch(Exception ex){
          JOptionPane.showConfirmDialog(null, ex); }   

    }//GEN-LAST:event_btnDelateSchooleActionPerformed

        
 int rowcount;
    private void addSchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSchoolActionPerformed
  int id;
   if(!txtNumSchool.isEnabled()){
     txtNumSchool.enable(true);
     txtNameSchool.enable(true);
     return;
 }
 if(txtNameSchool.getText().isEmpty()| txtNumSchool.getText().isEmpty()){
           JOptionPane.showConfirmDialog(null, "insert into fileds");
           return;
       }
      
  
           id =Integer.valueOf(txtNumSchool.getText());
           
           
           
         String Name=    txtNameSchool.getText();
       
        try{ 
   
   
            VoSchool schoole=new VoSchool();
            schoole.setIDSchool(id);
            schoole.setNameSchool(Name);

      schoole.setIDvilage(new DisplayValueModel1(comVilage.getSelectedIndex(),comVilage.getSelectedItem()));
    int        sckole
=SchoolINFDB.getInstance().insert(schoole);
  if(sckole>0){
  DefaultTableModel model1 = (DefaultTableModel) tabSchool.getModel();//getModel();

Object [] tab={  schoole.getIDSchool(),schoole.getNameSchool(),schoole.getIDvilage().DisplayMemeber};
model1.addRow(tab);
 JOptionPane.showConfirmDialog(this,"insert is sucessfuly");
  }
        }catch(Exception ex){
            JOptionPane.showConfirmDialog(this,ex);
        }

    }//GEN-LAST:event_addSchoolActionPerformed

    private void searchSchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSchoolActionPerformed
 if(!txtNumSchool.isEnabled()){
     txtNumSchool.enable(true);
     txtNameSchool.enable(true);
     return;
 }
       if(txtNameSchool.getText().isEmpty()& txtNumSchool.getText().isEmpty()){
           JOptionPane.showConfirmDialog(null, "insert into fileds");
           return;
       }
       if(Validation.isDigeit(txtNumSchool.getText()) &Validation.isText(txtNameSchool.getText())){
            JOptionPane.showConfirmDialog(null, "insert number fileds");
           return;   
           
       }
       
       int id=0;
       String Name="";
         id=    Integer.parseInt(txtNumSchool.getText()); 
          Name=    txtNameSchool.getText();
    
    
        try{
            
   setTable();
   mod.setNumRows(0);
            VoSchool schoole=new VoSchool();
            schoole.setIDSchool(id);
            schoole.setNameSchool(Name);
   VoSchool   sckole   =      SchoolINFDB.getInstance().search(schoole);
 
  
  DefaultTableModel model1 = (DefaultTableModel) tabSchool.getModel();//getModel();

comVilage.addItem(sckole.getIDvilage().toString());
Object [] tab={sckole.getNameSchool(),sckole.getIDSchool(),sckole.getIDvilage().DisplayMemeber};
model1.addRow(tab);

        }catch(Exception ex){
            JOptionPane.showConfirmDialog(this,ex);
        }
         
    }//GEN-LAST:event_searchSchoolActionPerformed

    private void newSchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSchoolActionPerformed
 
        
  
    
        
     

    }//GEN-LAST:event_newSchoolActionPerformed

    

    private void btnupdateScholeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateScholeActionPerformed
      
               
     String Name=     txtNameSchool.getText();
    int id=    Integer.valueOf(txtNumSchool.getText()); 
   
  
        try{
           VoSchool vo=new VoSchool();
         
          vo.setIDSchool(id);
          vo.setNameSchool(Name);
         vo.setIDvilage(new DisplayValueModel1(comVilage.getSelectedIndex(),comVilage.getSelectedItem()) );
     int rows   =   SchoolINFDB.getInstance().update(vo);
        
          if(rows>0){
  JOptionPane.showConfirmDialog(null,"update is sucessfuly");}
        }catch(Exception ex){
            JOptionPane.showConfirmDialog(this,ex);
        }

    }//GEN-LAST:event_btnupdateScholeActionPerformed
 DefaultTableModel mod;
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

   setTable();
   mod.setNumRows(0);
   VoSchool scol=new VoSchool();
   List<VoSchool> vo =new Vector<>();
mod.setNumRows(0);   
     // mod.fireTableRowsUpdated(0, mod.getRowCount())
   try{  
      
       
       
     
  for(VoSchool    vo1 : SchoolINFDB.getInstance().getAllElement()){
      Object []ob1={vo1.getIDvilage().DisplayMemeber,vo1.getNameSchool(),vo1.getIDSchool()};
       mod.addRow(ob1);
 
   }
 //  mod.addRow((Object[]) vo.toArray());
   }catch(Exception ex) {
        
        
    }
     //   mod.addRow();
        
      
     
    }//GEN-LAST:event_jToggleButton1ActionPerformed
private int  removeFromTable( ){
    setTable();
    rowcount=tabSchool.getSelectedRow();
         
         //   mod.getValueAt( "",row, row);
         mod.removeRow(rowcount);
         
         return rowcount;
}
    private void setTable(){
     mod =(DefaultTableModel ) tabSchool.getModel();
}
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(School.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(School.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(School.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(School.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new School().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addSchool;
    private javax.swing.JToggleButton btnDelateSchoole;
    private javax.swing.JToggleButton btnupdateSchole;
    private javax.swing.JComboBox<String> comVilage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblNumSchool;
    private javax.swing.JToggleButton newSchool;
    private javax.swing.JToggleButton searchSchool;
    private javax.swing.JTable tabSchool;
    private javax.swing.JTextField txtNameSchool;
    private javax.swing.JTextField txtNumSchool;
    // End of variables declaration//GEN-END:variables
}
