/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemmangmentinformation.DPL.Tranceformation;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import  systemmangmentinformation.DBL.Static.VilageINFDB;
/**
 *
 * @author shoeep
 */
public class Vilage extends javax.swing.JFrame {

    /**
     * Creates new form Vilage
     */
    public Vilage() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVilageNumber = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btnDelateVilage = new javax.swing.JToggleButton();
        btnAddVilage = new javax.swing.JToggleButton();
        btnSearchVilage = new javax.swing.JToggleButton();
        btnNewVilage = new javax.swing.JToggleButton();
        btnUpdateVilage = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabVilage = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("رقم المديرية");

        jLabel2.setText("اسم المديرية");

        btnDelateVilage.setText("حذف");
        btnDelateVilage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelateVilageActionPerformed(evt);
            }
        });

        btnAddVilage.setText("اضافة");
        btnAddVilage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVilageActionPerformed(evt);
            }
        });

        btnSearchVilage.setText("بحث");
        btnSearchVilage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchVilageActionPerformed(evt);
            }
        });

        btnNewVilage.setText("جديد");
        btnNewVilage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewVilageActionPerformed(evt);
            }
        });

        btnUpdateVilage.setText("تعديل");
        btnUpdateVilage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVilageActionPerformed(evt);
            }
        });

        tabVilage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم القرية", "اسم القرية"
            }
        ));
        jScrollPane1.setViewportView(tabVilage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnDelateVilage)
                .addGap(42, 42, 42)
                .addComponent(btnUpdateVilage)
                .addGap(38, 38, 38)
                .addComponent(btnSearchVilage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddVilage)
                .addGap(67, 67, 67)
                .addComponent(btnNewVilage)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(txtVilageNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVilageNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddVilage)
                    .addComponent(btnNewVilage)
                    .addComponent(btnSearchVilage)
                    .addComponent(btnUpdateVilage)
                    .addComponent(btnDelateVilage))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelateVilageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelateVilageActionPerformed
        try{

            VilageINFDB info=new VilageINFDB();
            int n=     Integer.parseInt(          txtVilageNumber.getText());

            boolean isdelete =      info.deleteRow(n);
            if(isdelete){

                String s="deleted successfuly";
                JOptionPane.showConfirmDialog(this,s);

            }

        }catch(Exception ex){
            JOptionPane.showConfirmDialog(this,ex);
        }
        txtVilageNumber.setText("");
        jTextField2.setText("");

    }//GEN-LAST:event_btnDelateVilageActionPerformed
int CurrentRow;
DefaultTableModel mod;
private    void setTyple(){
   mod= (DefaultTableModel)   tabVilage.getModel();

   
}
    private void btnAddVilageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVilageActionPerformed

        try{

            VilageINFDB info=new VilageINFDB();
            int n =     Integer.parseInt(          txtVilageNumber.getText());
            //String sql="insert into Branch(IDBranch ,NamePranch) values(" +n     + ",'"+jTextField2.getText()+"')";

            boolean b=  info.insert(n,jTextField2.getText());
            txtVilageNumber.setText("");
            jTextField2.setText("");
            String s="inserted successfuly";
            JOptionPane.showConfirmDialog(this,s);
        }catch(Exception ex){
            JOptionPane.showConfirmDialog(this,ex);
        }

    }//GEN-LAST:event_btnAddVilageActionPerformed

    private void btnSearchVilageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchVilageActionPerformed


        DefaultTableModel tbmodel = (DefaultTableModel)   tabVilage.getModel();
        try{
            VilageINFDB info=new VilageINFDB();
            String sql="select * from Vialge where IDvilage ="+Integer.parseInt(txtVilageNumber.getText())+
            "";
  Object obj []  =            info.selectConnditioal(sql);
   tbmodel.addRow( obj);
            //  jTextField1.setText(info.selectConnditioalInt(sql)+"");

        }catch(Exception ex){
            JOptionPane.showConfirmDialog(this,ex,"connection error ",1);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchVilageActionPerformed

    private void btnNewVilageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewVilageActionPerformed

        txtVilageNumber.setText("");
        jTextField2.setText("");

    }//GEN-LAST:event_btnNewVilageActionPerformed

    private void btnUpdateVilageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVilageActionPerformed
        try{

            VilageINFDB info=new VilageINFDB();
            int n=     Integer.parseInt(txtVilageNumber.getText());

            int m=     info.update(n,jTextField2.getText());
            if(m !=-1){
                String s="update successfuly";
                JOptionPane.showConfirmDialog(this,s);

            }
            txtVilageNumber.setText("");
            jTextField2.setText("");
        }catch(Exception ex){
            JOptionPane.showConfirmDialog(this,ex);
        }

    }//GEN-LAST:event_btnUpdateVilageActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vilage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vilage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vilage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vilage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vilage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAddVilage;
    private javax.swing.JToggleButton btnDelateVilage;
    private javax.swing.JToggleButton btnNewVilage;
    private javax.swing.JToggleButton btnSearchVilage;
    private javax.swing.JToggleButton btnUpdateVilage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tabVilage;
    private javax.swing.JTextField txtVilageNumber;
    // End of variables declaration//GEN-END:variables
}
